# permissions for end users to edit argoworkflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: argoworkflow-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: argo-workflow-operator
    app.kubernetes.io/part-of: argo-workflow-operator
    app.kubernetes.io/managed-by: kustomize
  name: argoworkflow-editor-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - argoworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - argoworkflows/status
  verbs:
  - get
